# Generated by Django 4.0.3 on 2022-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_historial_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='ID_Canciones',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historial',
            name='ID_Usuario',
            field=models.CharField(max_length=30),
        ),
    ]
